version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
